In [13]:
import numpy as np
nutrient_needs=np.array([
    [120,60,80],
    [150,75,100],
    [100,50,70]
])
fertilizer_composition=np.array([
    [0.20, 0.10, 0.15],
    [0.15, 0.20, 0.10],
    [0.10, 0.15, 0.25]
])
print("nutrient requirements(kg/ha):")
print(nutrient_needs)
print("\nfertilizer composition(%):")
print(fertilizer_composition)

print("\ntranspose nutrient needs(nutrients crops):")
print(nutrient_needs.T)

total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f"\ntotal nutrients needed per crop:{total_nutrients_per_crop}kg/ha")

fertilizer_application=np.array([100,100,100])
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f"\nnutrients from 100kg each fertilizer:{nutrients_delivered}")

det=np.linalg.det(fertilizer_composition)
print(f"\ndeterminant of fertilizer matrix:{det:.6f}")

scaling=np.eye(3)*1.1
enhanced_needs=np.dot(nutrient_needs,scaling)
print("\nenhanced nutrient needs(10% increase):")
print(enhanced_needs)

nutrient requirements(kg/ha):
[[120  60  80]
 [150  75 100]
 [100  50  70]]

fertilizer composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

transpose nutrient needs(nutrients crops):
[[120 150 100]
 [ 60  75  50]
 [ 80 100  70]]

total nutrients needed per crop:[260 325 220]kg/ha

nutrients from 100kg each fertilizer:[45. 45. 50.]

determinant of fertilizer matrix:0.004625

enhanced nutrient needs(10% increase):
[[132.   66.   88. ]
 [165.   82.5 110. ]
 [110.   55.   77. ]]
