In [1]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A@B

array([[19, 22],
       [43, 50]])

In [5]:
#Transpose
import numpy as np
matrix=[[1,2],
   [3,4]]
transposed=np.transpose(matrix)
print(transposed)

[[1 3]
 [2 4]]


In [6]:
#matrix determinant(2*2)
import numpy as np
A=[[1,2],
   [3,4]]
det=np.linalg.det(A)
print(det)

-2.0000000000000004


In [9]:
#(3*3)
import numpy as np
A=[[1,2,3],
   [7,4,5],
   [9,6,7]]
det=np.linalg.det(A)
print(det)


7.999999999999995


In [10]:
#matrix inverse
import numpy as np
A=[[1,2],
   [3,4]]
inverse=np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
#matrix ranking
import numpy as np
A=[[1,2],
   [3,4]]
rank=np.linalg.matrix_rank(A)
print(rank)

2


In [15]:
#eigenvalues and eigenvectors
import numpy as np
A=[[1,2],
   [3,4]]
eigenvalues,eigenvectors=np.linalg.eig(A)
print(eigenvalues,eigenvectors)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [18]:
#solving linear system
import numpy as np
A=[[1,2],
 [3,4]]
B=[[5,6],
   [7,8]]
Ax=B
solution=np.linalg.solve(A,B)
print(solution)

[[-3. -4.]
 [ 4.  5.]]
