In [ ]:
#1D
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
#0-D
import numpy as np
arr=np.array(42)
print(arr)

42


In [ ]:
#2D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#number of dimensions
import numpy as pd
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#higher dimensional arrays
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [ ]:
#array indexing
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
#using built in functions
import numpy as np
zeros=np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
range_arr=np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
import numpy as np
linspace=np.linspace(0,1,5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#list/tuple into list
import numpy as np
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.dtype)

(2, 3)
int64


In [ ]:
print(a.size)

6


In [ ]:
print(a.ndim)

2


In [ ]:
b=np.sum(a)
print(b)

21


In [ ]:
#column-wise mean
np.mean(a,axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
#row-wise
np.mean(a,axis=1)

array([2., 5.])

In [ ]:
b=np.max(a)
c=np.min(a)
print(b)
print(c)

6
1


In [ ]:
#index of exteme value
b=np.argmax([10,20,30])
print(b)


2


In [2]:
import numpy as np
crop_yields=np.array([
    [12.5, 13.2, 14.1, 13.8, 15.2],
    [10.3, 11.5, 10.8, 12.1, 11.9],
    [15.1, 14.8, 16.2, 15.5, 16.8],
    [11.2, 10.9, 12.3, 11.7, 12.8]
])
print('crop yields array(tons):')
print(crop_yields)
print(f'\nshape:{crop_yields.shape}')
print(f'total elements:{crop_yield.size}')
print(f'number of dimensions:{crop_yield.ndim}')

crop yields array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

shape:(4, 5)
total elements:20
number of dimensions:2
