In [ ]:
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
    ])
mask=np.array([True,False,True])
print(a[mask])



[[1 2]
 [5 6]]


In [2]:
import numpy as np
a=([
    [1,2],
    [3,4]
])
b=([[1,2],
    [3,4],
    [5,6]
    ])
c=a+b
print(c)

[[1, 2], [3, 4], [1, 2], [3, 4], [5, 6]]


In [12]:
import numpy as np
a=np.arange(50).reshape(10,5)
selected_rows=a[a[:,0]>20]
print(selected_rows)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [16]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
c=a[(a>2)&(a<6)]
print(c)


[3 4 5]


In [35]:
import numpy as np
a=np.array([1,2,3,4,5,6])
c=a[a>3]=0
print(c)


0


In [36]:
import numpy as np
a=np.array([1,2,3])
c=2*a
print(c)

[2 4 6]


In [47]:
import numpy as np
a=np.array([
    [1,2,3],
    [4,5,6]
    ])
b=np.array([1,2,3])
c=a*b
print(c)

[[ 1  4  9]
 [ 4 10 18]]


In [58]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
c=a[a[:,1]%2==0]
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [60]:
a=np.array([1,2,3,4,5,6])
mask=np.array([True,False,True,False,True,False])
b=a[mask]*10
print(b)

[10 30 50]


In [75]:
import numpy as np
a=np.array([[1],
           [2],
           [3],
           [4],
           [5]])
print(a.shape)

(5, 1)


In [78]:
import numpy as np
a=np.array([10,20,30,40,50])
mask=a>25
a[mask]
idx=np.array([2,3])
a[idx]

array([30, 40])

In [82]:
import numpy as np
x=np.arange(10)
x[x%2==0]*=2
print(x)

[ 0  1  4  3  8  5 12  7 16  9]


In [86]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
a[b]

array([1, 3, 5])

In [91]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a[:,[False,True]]

array([[2],
       [4],
       [6]])

In [95]:
import numpy as np
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
mask=np.array([True,False,True])
print(arr[mask])

[[ 1  2  3  4]
 [ 9 10 11 12]]
